# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    
jobs:

  
  build:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout Step
    - uses: actions/checkout@v2
    
    # Setup Step
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Validation Step
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    # Build Step
    - name: Build with Gradle
      run: ./gradlew build
      
    # Package Step
    - uses: actions/upload-artifact@v3
      with:
        name: amazon-macie-finding-data-reveal-artifact
        path: reveal/build/libs
